### ISSUE TITLE
Implement folder move script

### ISSUE THREAD

**Issue by badvision** [badvision/acs-aem-commons#3]
Moving folders in AEM today is a very costly process.  It is probably faster, albeit with some risk, to break this up into a multi-stage process instead of a single commit:

Step 1: Validate.  This should check if all nodes can be moved and that there are no ACL issues.  All failures should be considered terminal and the user should get a detailed report of what prevented the operation.
Step 2: Clone folder structure.  As much of the original folder metadata should be copied over where possible, especially ACLs.  Failures in this step should be considered fatal and the result should be that the new folders should be removed and a report of errors sent to the user.
Step 3: Move each non-folder node.  With the folder structure in place this step should be successful.  This step should be performed as a system user to bypass additional ACL checks, since they were already checked in step 1.  Failures in the step should not be considered terminal but should be reported in the end.  Any failures in this step should, however, prevent Step 4 from executing.
Step 4: Remove old folder structure.

**Comment by davidjgonzalez** [comment]
Unsure which "folders" are in question here.. but will this also (optionally) update references? and/or adjust/republish?

**Comment by badvision** [comment]
Folders are sling:OrderedFolder and sling:Folder -- Maybe also nt:unstructured.  The primary use case is for reorganizing assets.  How are assets re-published today when this happens?  Manually or automatically?

**Comment by bstopp** [comment]
I know that the _delete_ of the published asset is automatic. It is required as part of the delete operation. (hence you need replicate permission to _actually_ delete anything). I do not believe that after the move the new items are automatically re-published.

**Comment by ireasor** [comment]
If you take a look at the product code for a move operation, it is actually really complicated.  References, deactivation, reactivation, etc, all need to be accounted for.

**Comment by badvision** [comment]
Yes, and it will still be a part of it.  The difference is that this script moves the assets one by one as separate commits instead of trying to shove it into one big, expensive transaction.  I think it will scale better and lessen or eliminate the chance that the JCR will become unresponsive for large tree moves.

**Comment by kaushalmall** [comment]
Not sure how doing multiple commits is faster. Should probably move ~1000 before a commit. 

> The difference is that this script moves the assets one by one as separate commits instead of trying to shove it into one big, expensive transaction

**Comment by badvision** [comment]
The major difference is getting a progress indicator in case it still takes a long time.  A 15 minute pause with no user feedback at all is quite terrible!

**Comment by badvision** [comment]
Also I'm not sure 1000 is a good idea either because one error and you have 999 other items which did not get saved correctly.  Performance testing for one customer shows it's taking several minutes to move 200 assets under load.  It would be better, instead, to not hard-code the number and let it be user-definable.

**Comment by davidjgonzalez** [comment]
IIUC there is a "sweet" spot in batch size depending on what's being committed ..with the trade offs:

1) The transactional overhead of a large number of tiny commits
2) The resource lock overhead of few massive commits

Likely over engineering, but might be cool to have ThrottledTaskRunner auto-adjust-batch size to try to hit a configurable "target time to commit" metric (not sure what that # would be, 500ms?)

**Comment by badvision** [comment]
To quote Luke Skywalker: "That's okay, I'd like to keep it on manual for a while."

**Comment by badvision** [comment]
Moving an asset which has many renditions, dozens or more metadata subnodes, and potentially many sub-assets is already a lot of changes for "one" action.

**Comment by badvision** [comment]
The basics of the script are done but there is nothing to handle publish/unpublish at this point in time.
